#!/usr/bin/env python
import os

from auto_api import AutoApi

# Set autoapi config
os.environ['AUTOAPI_SETTINGS'] = os.path.join(
    os.path.dirname(os.path.realpath(__file__)),
    'server.cfg'
)

# Create and run autoapi
AutoApi(auth=True).run()
