#!/usr/bin/env python
import os

from ApiSDF import app


os.environ['APISDF_SETTINGS'] = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'server.cfg')

app.run(host='0.0.0.0', port=8686, use_reloader=True, debug=True)
