name: docker

# on:
#   release:
#     types: [published]
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: autoapi/autoapi
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          target: runtime-autoapi
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: fvalverd/AutoApi/autoapi
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tag_with_ref: true
          target: runtime-autoapi